# G29 Bridge 配置参数

g29_bridge_node:
  ros__parameters:
    udp_port: 9999
    max_speed: 1.0
    max_steering_angle: 45.0
    ackermann_topic: "ackermann_cmd"
    timeout_sec: 0.5

camera_streamer:
  ros__parameters:
    image_topic: "/image"
    http_port: 8080

origincar_base:
  ros__parameters:
    usart_port_name: "/dev/ttyACM0"
    serial_baud_rate: 115200
    robot_frame_id: "base_footprint"
    odom_frame_id: "odom_combined"
    cmd_vel: "cmd_vel"
    akm_cmd_vel: "ackermann_cmd"
    use_direct_angle: true
